In [3]:
# how to read data from different sources like json and etc

import pandas as pd
from io import StringIO

Data = '{"employee": "James", "email": "james@gmail.com", "job_profile":[{"title": "Team Lead", "Title2": "Sr Machine learning Developer"}]}'

df = pd.read_json(StringIO(Data)) # storing this data frame in df

In [ ]:
df.to_json() # this is for json conversion with index

'{"employee":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title":"Team Lead","Title2":"Sr Machine learning Developer"}}}'

In [ ]:
df.to_json(orient='index')

'{"0":{"employee":"James","email":"james@gmail.com","job_profile":{"title":"Team Lead","Title2":"Sr Machine learning Developer"}}}'

In [ ]:
# here we are using one sample csv file and read through data frames from pandas

df = pd.read_csv("Sample CSV file for importing contacts.csv")
df.head()

#now if you want to convert back to csv then 



df.to_csv("wine.csv")

,Title,First Name,Middle Name,Last Name,Suffix,Company,Department,Job Title,Business Street,Business Street 2,...,Private,Profession,Referred By,Sensitivity,Spouse,User 1,User 2,User 3,User 4,Web Page
0,NaN,Anita,NaN,Jorgensen,NaN,Contoso,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.microsoft.com/
1,NaN,Anne-Mette,NaN,Olesen,NaN,Contoso,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Dorena,NaN,Paschke,NaN,Contoso,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Kemal,NaN,Celik,NaN,Contoso,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Shiori,NaN,Inoue,NaN,Contoso,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd


url="https://en.wikipedia.org/wiki/Mobile_country_code"

df_list = pd.read_html(url, match="Country", header=0, storage_options={'User-Agent':'Mozilla/5.0'})

df = df_list[0]
df.head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

In [ ]:
# reading (xlsx) excel file

pd.read_excel()