In [1]:
import pandas as pd 

from sklearn.preprocessing import OneHotEncoder

In [2]:
# create a simple dataframe

df = pd.DataFrame({
    'color': ['red','blue', 'green', 'green', 'red', 'blue']    
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
## create an instance of oneHotEncoder

encoder = OneHotEncoder()

In [10]:
# perform fit and transform

encoded = encoder.fit_transform(df[['color']]).toarray()

In [11]:
import pandas as pd

encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
# when you got new data then what will happen

encoder.transform([['blue']]).toarray()

In [ ]:
pd.concat([df, encoder_df], axis=1)